name: Dreamcatcher
favicon: null
layout_spectrum: 0.99368
typography_spectrum: 0.85722
title: Traveling through the six senses
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8710105675272644
  lightness: 0.8722520400770009
  saturation: 0.6507408565375954
  rhythmicContrast: 0.9652193745132536
purpose: []
